name: cKitPVP
main: me.theremixpvp.ckitpvp.Main
version: 0.7
author: TheRemixPvP
commands:
  stats:
    description: Get stats on yourself or other players.
  credits:
    description: View your credits.
    aliases: [cr, c]
  pvp:
    description: Equip the PVP kit.
  tank:
    description: Equip the tank kit.
  fisherman:
    description: Equip the Fisherman kit.
  grappler:
    description: Equip the Grappler kit.
  hulk:
    description: Equip the Hulk kit.
  dodge:
    description: Equip the Dodge kit.
  lucky:
    description: Equip the Lucky kit.
  rusher:
    description: Equip the Rusher kit.
  sniper:
    description: Equip the Sniper kit.
  visionmaster:
    description: Equip the VisionMaster kit.
  ez:
    description: Equip the EZ kit.
  acrobat:
    description: Equip the Acrobat kit.
  ninja:
    description: Equip the Ninja kit.
  kits:
    description: List your kits.
  kit:
    description: Check another player's kit.
  bank:
    description: Open your personal bank.
  soup:
    description: Get a chest full of soup.
  test:
    description: Testing things….
  hat:
    description: Get a hat…duh….
  more:
    description: Get a stack of the item you're holding.
  shop:
    description: Open the shop.
permissions:
  ckitpvp.admin:
    description: Admin commands
    permission: ckitpvp.admin
  ckitpvp.shop.admin:
    description: Use admin options in the shop.
    permission: ckitpvp.shop.admin
  ckitpvp.soup:
    description: Allow access to /soup
    permission: ckitpvp.soup
  ckitpvp.bank.small:
    description: Access to a small bank.
    permission: ckitpvp.bank.small
  ckitpvp.bank.large:
    description: Access to a large bank.
    permission: ckitpvp.bank.large
  ckitpvp.bank.reset:
    description: Reset someone's bank
    permission: ckitpvp.bank.reset