name: cKitPVP
main: me.theremixpvp.ckitpvp.Main
version: 0.1
author: TheRemixPvP
commands:
  stats:
    description: Get stats on yourself or other players.
  pvp:
    description: Equip the PVP kit.
  tank:
    description: Equip the tank kit.
  sniper:
    description: Equip the Sniper kit.
  kitshop:
    description: View the kit shop and buy kits.
  kits:
    description: List your kits.
  kit:
    description: Check another player's kit!