name: cKitPVP
main: me.theremixpvp.ckitpvp.KitPvP
version: "1.0"
author: TheRemixPvP
commands:
  stats:
    description: Get stats on yourself or other players.
  credits:
    description: View your credits.
    aliases: [cr, c]
  kits:
    description: List your kits.
  kit:
    description: Check another player's kit.
  bank:
    description: Open your personal bank.
  soup:
    description: Get a chest full of soup.
  hat:
    description: Get a hat
  more:
    description: Get a stack of the item you're holding.
  shop:
    description: Open the shop.
  playerdata:
    description: Manipulate player's stats and data
    aliases: [pdata, pd]
permissions:
  ckitpvp.admin:
    description: Admin commands
    permission: ckitpvp.admin
  ckitpvp.shop.admin:
    description: Use admin options in the shop.
    permission: ckitpvp.shop.admin
  ckitpvp.soup:
    description: Allow access to /soup
    permission: ckitpvp.soup
  ckitpvp.bank.small:
    description: Access to a small bank.
    permission: ckitpvp.bank.small
  ckitpvp.bank.large:
    description: Access to a large bank.
    permission: ckitpvp.bank.large
  ckitpvp.bank.reset:
    description: Reset someone's bank
    permission: ckitpvp.bank.reset